/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDqcIndexRouteImport } from './routes/_authenticated/dqc/index'
import { Route as AuthenticatedDesignerIndexRouteImport } from './routes/_authenticated/designer/index'
import { Route as AuthenticatedCoordIndexRouteImport } from './routes/_authenticated/coord/index'
import { Route as AuthenticatedDesignerNewRouteImport } from './routes/_authenticated/designer/new'
import { Route as AuthenticatedDqcPaperIdRouteImport } from './routes/_authenticated/dqc/paper.$id'
import { Route as AuthenticatedDesignerPaperIdRouteImport } from './routes/_authenticated/designer/paper.$id'
import { Route as AuthenticatedCoordPaperIdRouteImport } from './routes/_authenticated/coord/paper.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDqcIndexRoute = AuthenticatedDqcIndexRouteImport.update({
  id: '/dqc/',
  path: '/dqc/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignerIndexRoute =
  AuthenticatedDesignerIndexRouteImport.update({
    id: '/designer/',
    path: '/designer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordIndexRoute = AuthenticatedCoordIndexRouteImport.update({
  id: '/coord/',
  path: '/coord/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignerNewRoute =
  AuthenticatedDesignerNewRouteImport.update({
    id: '/designer/new',
    path: '/designer/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDqcPaperIdRoute = AuthenticatedDqcPaperIdRouteImport.update({
  id: '/dqc/paper/$id',
  path: '/dqc/paper/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignerPaperIdRoute =
  AuthenticatedDesignerPaperIdRouteImport.update({
    id: '/designer/paper/$id',
    path: '/designer/paper/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordPaperIdRoute =
  AuthenticatedCoordPaperIdRouteImport.update({
    id: '/coord/paper/$id',
    path: '/coord/paper/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/designer/new': typeof AuthenticatedDesignerNewRoute
  '/coord/': typeof AuthenticatedCoordIndexRoute
  '/designer/': typeof AuthenticatedDesignerIndexRoute
  '/dqc/': typeof AuthenticatedDqcIndexRoute
  '/coord/paper/$id': typeof AuthenticatedCoordPaperIdRoute
  '/designer/paper/$id': typeof AuthenticatedDesignerPaperIdRoute
  '/dqc/paper/$id': typeof AuthenticatedDqcPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/designer/new': typeof AuthenticatedDesignerNewRoute
  '/coord': typeof AuthenticatedCoordIndexRoute
  '/designer': typeof AuthenticatedDesignerIndexRoute
  '/dqc': typeof AuthenticatedDqcIndexRoute
  '/coord/paper/$id': typeof AuthenticatedCoordPaperIdRoute
  '/designer/paper/$id': typeof AuthenticatedDesignerPaperIdRoute
  '/dqc/paper/$id': typeof AuthenticatedDqcPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/designer/new': typeof AuthenticatedDesignerNewRoute
  '/_authenticated/coord/': typeof AuthenticatedCoordIndexRoute
  '/_authenticated/designer/': typeof AuthenticatedDesignerIndexRoute
  '/_authenticated/dqc/': typeof AuthenticatedDqcIndexRoute
  '/_authenticated/coord/paper/$id': typeof AuthenticatedCoordPaperIdRoute
  '/_authenticated/designer/paper/$id': typeof AuthenticatedDesignerPaperIdRoute
  '/_authenticated/dqc/paper/$id': typeof AuthenticatedDqcPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/designer/new'
    | '/coord/'
    | '/designer/'
    | '/dqc/'
    | '/coord/paper/$id'
    | '/designer/paper/$id'
    | '/dqc/paper/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/designer/new'
    | '/coord'
    | '/designer'
    | '/dqc'
    | '/coord/paper/$id'
    | '/designer/paper/$id'
    | '/dqc/paper/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/designer/new'
    | '/_authenticated/coord/'
    | '/_authenticated/designer/'
    | '/_authenticated/dqc/'
    | '/_authenticated/coord/paper/$id'
    | '/_authenticated/designer/paper/$id'
    | '/_authenticated/dqc/paper/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dqc/': {
      id: '/_authenticated/dqc/'
      path: '/dqc'
      fullPath: '/dqc/'
      preLoaderRoute: typeof AuthenticatedDqcIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/designer/': {
      id: '/_authenticated/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof AuthenticatedDesignerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coord/': {
      id: '/_authenticated/coord/'
      path: '/coord'
      fullPath: '/coord/'
      preLoaderRoute: typeof AuthenticatedCoordIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/designer/new': {
      id: '/_authenticated/designer/new'
      path: '/designer/new'
      fullPath: '/designer/new'
      preLoaderRoute: typeof AuthenticatedDesignerNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dqc/paper/$id': {
      id: '/_authenticated/dqc/paper/$id'
      path: '/dqc/paper/$id'
      fullPath: '/dqc/paper/$id'
      preLoaderRoute: typeof AuthenticatedDqcPaperIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/designer/paper/$id': {
      id: '/_authenticated/designer/paper/$id'
      path: '/designer/paper/$id'
      fullPath: '/designer/paper/$id'
      preLoaderRoute: typeof AuthenticatedDesignerPaperIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coord/paper/$id': {
      id: '/_authenticated/coord/paper/$id'
      path: '/coord/paper/$id'
      fullPath: '/coord/paper/$id'
      preLoaderRoute: typeof AuthenticatedCoordPaperIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDesignerNewRoute: typeof AuthenticatedDesignerNewRoute
  AuthenticatedCoordIndexRoute: typeof AuthenticatedCoordIndexRoute
  AuthenticatedDesignerIndexRoute: typeof AuthenticatedDesignerIndexRoute
  AuthenticatedDqcIndexRoute: typeof AuthenticatedDqcIndexRoute
  AuthenticatedCoordPaperIdRoute: typeof AuthenticatedCoordPaperIdRoute
  AuthenticatedDesignerPaperIdRoute: typeof AuthenticatedDesignerPaperIdRoute
  AuthenticatedDqcPaperIdRoute: typeof AuthenticatedDqcPaperIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDesignerNewRoute: AuthenticatedDesignerNewRoute,
  AuthenticatedCoordIndexRoute: AuthenticatedCoordIndexRoute,
  AuthenticatedDesignerIndexRoute: AuthenticatedDesignerIndexRoute,
  AuthenticatedDqcIndexRoute: AuthenticatedDqcIndexRoute,
  AuthenticatedCoordPaperIdRoute: AuthenticatedCoordPaperIdRoute,
  AuthenticatedDesignerPaperIdRoute: AuthenticatedDesignerPaperIdRoute,
  AuthenticatedDqcPaperIdRoute: AuthenticatedDqcPaperIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
