/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDqcIndexRouteImport } from './routes/_authenticated/dqc/index'
import { Route as AuthenticatedDesignerIndexRouteImport } from './routes/_authenticated/designer/index'
import { Route as AuthenticatedCoordIndexRouteImport } from './routes/_authenticated/coord/index'
import { Route as AuthenticatedDesignerNewRouteImport } from './routes/_authenticated/designer/new'
import { Route as AuthenticatedDqcPaperIdRouteImport } from './routes/_authenticated/dqc/paper.$id'
import { Route as AuthenticatedDesignerPaperIdRouteImport } from './routes/_authenticated/designer/paper.$id'
import { Route as AuthenticatedCoordPaperIdRouteImport } from './routes/_authenticated/coord/paper.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDqcIndexRoute = AuthenticatedDqcIndexRouteImport.update({
  id: '/_authenticated/dqc/',
  path: '/dqc/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDesignerIndexRoute =
  AuthenticatedDesignerIndexRouteImport.update({
    id: '/_authenticated/designer/',
    path: '/designer/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCoordIndexRoute = AuthenticatedCoordIndexRouteImport.update({
  id: '/_authenticated/coord/',
  path: '/coord/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDesignerNewRoute =
  AuthenticatedDesignerNewRouteImport.update({
    id: '/_authenticated/designer/new',
    path: '/designer/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDqcPaperIdRoute = AuthenticatedDqcPaperIdRouteImport.update({
  id: '/_authenticated/dqc/paper/$id',
  path: '/dqc/paper/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDesignerPaperIdRoute =
  AuthenticatedDesignerPaperIdRouteImport.update({
    id: '/_authenticated/designer/paper/$id',
    path: '/designer/paper/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCoordPaperIdRoute =
  AuthenticatedCoordPaperIdRouteImport.update({
    id: '/_authenticated/coord/paper/$id',
    path: '/coord/paper/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designer/new': typeof AuthenticatedDesignerNewRoute
  '/coord/': typeof AuthenticatedCoordIndexRoute
  '/designer/': typeof AuthenticatedDesignerIndexRoute
  '/dqc/': typeof AuthenticatedDqcIndexRoute
  '/coord/paper/$id': typeof AuthenticatedCoordPaperIdRoute
  '/designer/paper/$id': typeof AuthenticatedDesignerPaperIdRoute
  '/dqc/paper/$id': typeof AuthenticatedDqcPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designer/new': typeof AuthenticatedDesignerNewRoute
  '/coord': typeof AuthenticatedCoordIndexRoute
  '/designer': typeof AuthenticatedDesignerIndexRoute
  '/dqc': typeof AuthenticatedDqcIndexRoute
  '/coord/paper/$id': typeof AuthenticatedCoordPaperIdRoute
  '/designer/paper/$id': typeof AuthenticatedDesignerPaperIdRoute
  '/dqc/paper/$id': typeof AuthenticatedDqcPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/designer/new': typeof AuthenticatedDesignerNewRoute
  '/_authenticated/coord/': typeof AuthenticatedCoordIndexRoute
  '/_authenticated/designer/': typeof AuthenticatedDesignerIndexRoute
  '/_authenticated/dqc/': typeof AuthenticatedDqcIndexRoute
  '/_authenticated/coord/paper/$id': typeof AuthenticatedCoordPaperIdRoute
  '/_authenticated/designer/paper/$id': typeof AuthenticatedDesignerPaperIdRoute
  '/_authenticated/dqc/paper/$id': typeof AuthenticatedDqcPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designer/new'
    | '/coord/'
    | '/designer/'
    | '/dqc/'
    | '/coord/paper/$id'
    | '/designer/paper/$id'
    | '/dqc/paper/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/designer/new'
    | '/coord'
    | '/designer'
    | '/dqc'
    | '/coord/paper/$id'
    | '/designer/paper/$id'
    | '/dqc/paper/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/designer/new'
    | '/_authenticated/coord/'
    | '/_authenticated/designer/'
    | '/_authenticated/dqc/'
    | '/_authenticated/coord/paper/$id'
    | '/_authenticated/designer/paper/$id'
    | '/_authenticated/dqc/paper/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedDesignerNewRoute: typeof AuthenticatedDesignerNewRoute
  AuthenticatedCoordIndexRoute: typeof AuthenticatedCoordIndexRoute
  AuthenticatedDesignerIndexRoute: typeof AuthenticatedDesignerIndexRoute
  AuthenticatedDqcIndexRoute: typeof AuthenticatedDqcIndexRoute
  AuthenticatedCoordPaperIdRoute: typeof AuthenticatedCoordPaperIdRoute
  AuthenticatedDesignerPaperIdRoute: typeof AuthenticatedDesignerPaperIdRoute
  AuthenticatedDqcPaperIdRoute: typeof AuthenticatedDqcPaperIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dqc/': {
      id: '/_authenticated/dqc/'
      path: '/dqc'
      fullPath: '/dqc/'
      preLoaderRoute: typeof AuthenticatedDqcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/designer/': {
      id: '/_authenticated/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof AuthenticatedDesignerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coord/': {
      id: '/_authenticated/coord/'
      path: '/coord'
      fullPath: '/coord/'
      preLoaderRoute: typeof AuthenticatedCoordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/designer/new': {
      id: '/_authenticated/designer/new'
      path: '/designer/new'
      fullPath: '/designer/new'
      preLoaderRoute: typeof AuthenticatedDesignerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dqc/paper/$id': {
      id: '/_authenticated/dqc/paper/$id'
      path: '/dqc/paper/$id'
      fullPath: '/dqc/paper/$id'
      preLoaderRoute: typeof AuthenticatedDqcPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/designer/paper/$id': {
      id: '/_authenticated/designer/paper/$id'
      path: '/designer/paper/$id'
      fullPath: '/designer/paper/$id'
      preLoaderRoute: typeof AuthenticatedDesignerPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coord/paper/$id': {
      id: '/_authenticated/coord/paper/$id'
      path: '/coord/paper/$id'
      fullPath: '/coord/paper/$id'
      preLoaderRoute: typeof AuthenticatedCoordPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedDesignerNewRoute: AuthenticatedDesignerNewRoute,
  AuthenticatedCoordIndexRoute: AuthenticatedCoordIndexRoute,
  AuthenticatedDesignerIndexRoute: AuthenticatedDesignerIndexRoute,
  AuthenticatedDqcIndexRoute: AuthenticatedDqcIndexRoute,
  AuthenticatedCoordPaperIdRoute: AuthenticatedCoordPaperIdRoute,
  AuthenticatedDesignerPaperIdRoute: AuthenticatedDesignerPaperIdRoute,
  AuthenticatedDqcPaperIdRoute: AuthenticatedDqcPaperIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
